version: '3'

services:

  # Eclipse Mosquitto MQTT Broker
  mosquitto:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MOSQUITTO_VERSION=${MOSQUITTO_VERSION:-latest}
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    image: eclipse-mosquitto:${MOSQUITTO_VERSION:-latest}
    container_name: mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    networks:
      - edge
      
  nodered:
    build: 
      context: ./nodered
      dockerfile: Dockerfile
    #image: nodered/node-red
    container_name: nodered
    restart: always
    environment:
      - TZ=America/Sao_Paulo
    ports: 
      - 1880:1880
    volumes:
      - noderedData:/data
    networks:
      - edge
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes: 
      - grafanaData:/var/lib/grafana
    networks:
      - edge     

  influxdb:
    image: influxdb:2.4.0
    container_name: influxdb
    restart: always
    environment:
      INFLUXDB_DB: DBONE
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: influx
      INFLUXDB_ADMIN_PASSWORD: influx
      INFLUXDB_USER: root
      INFLUXDB_USER_PASSWORD: secret
    ports:
      - "8082:8082"
      - "8086:8086"
      - "8089:8089"
    volumes:
      - influxData:/var/lib/influxdb
    networks: 
      - edge       
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: sol@solucoes
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8001:80
    volumes:
      dbdata:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000

#Create Volumes for persistent Storage
volumes:
  noderedData:
  influxData:
  grafanaData:
  dbdata:
# Create internal link network for Containers
networks:
  edge:      

