FROM nodered/node-red:latest

RUN npm install node-red-contrib-telegrambot    # instala o nó do telegrambot

RUN npm install node-red-node-mysql             # instala o nó do mysql

#COPY nodered/settings.js /node-red-data/settings.js
#RUN cp /iot/nodered/settings.txt /var/lib/docker/volumes/iot_nodered/_data/e.txt
#RUN cp /iot/nodered/settings.txt /iot
#RUN cp ./config/a.txt /a.txt
# cd /var/lib/docker/volumes/iot3_node-red-data/_data

#RUN npm install node-red-contrib-whatsapp-link
#RUN npm install node-red-contrib-telegrambot
#RUN npm install node-red-node-mysql
